{% set name = "rsync" %}
{% set version = "3.2.0" %}
{% set config_hash = "04b07fc6d9ad4fd2be7434c9ce8b03341e54ca02" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://www.samba.org/ftp/{{ name }}/src/{{ name }}-{{ version }}.tar.gz
    sha256: 90127fdfb1a0c5fa655f2577e5495a40907903ac98f346f225f867141424fa25
    patches:
      - 0001-removed-devices-test.patch
  - fn: config-updated.guess
    url: http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb={{ config_hash }}
    sha256: 8202b7fde008212d6d36cccf219480f5d54cddb5452b241f47c51cb5c054193b
  - fn: config-updated.sub
    url: http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb={{ config_hash }}
    sha256: 729711e8aa3228db4a3adea9ca5d60de184969a1537ac874477ce5676bee8464

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - perl
    - {{ compiler('c') }}
    - make
  host:
    - zlib
    - popt 1.16
  run:
    - zlib
    - popt 1.16

test:
  commands:
    - conda inspect linkages $PKG_NAME  # [not win]
    - conda inspect objects $PKG_NAME  # [osx]
    - rsync --help

about:
  home: https://rsync.samba.org/
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING
  summary: Tool for fast incremental file transfer

  description: |
    rsync is an open source utility that provides fast incremental file transfer.
  doc_url: https://rsync.samba.org/documentation.html
  dev_url: https://git.samba.org/?p=rsync.git

extra:
  recipe-maintainers:
    - notestaff
    - sodre
