appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: HLgBNjjx7uW8BzhuhX7iPCXSE3KGaszH+NLj5b4MmBGvheC0qvvEOqpQU87uRifJc9Rr5lgl1QzZwOMecArXyo+CbO7ugsP7f5sr/nNQZLXv/PvRh8pUXIdOvLzyRdym4wMzOko7zQEVZZevr88cAdRk2uD1HINCnMLbPYgB6oI44Lnv9MWXs+dRn5dFUSRpEFgX7pRo19e92jNPLJvmtsG0XWm3JdGslQPnMg6A73SABinLYPkG+ue54tl0UlLoi2ZC1mDa63clyqTzF230HXpPrgYdFEuL5/tKJls9v+MpRkxax2y14XhLFkQczgVM4UvBnNGn0U5DOII4JZ3m1Gai36lFbPNwR0moRgG5PnQx89XcunEuU5+qu5cen23fKyJUNS8jEplHEWDPLXvyPtHyUvvrW3vT5DjQSKDtyeUMl9HJfL4qFL7Y1ahK6ZU/9QK0ci+8BTrSEIH5Rk00IY0F9os2mTYtGVfQq4VKbAfmiAcNbm+WSTYU/wcZpIB66KsLyodAf0K4NxIIQ2bFRtK2lwokD8mG1/cd+gkuMFVSRmZeBkszhdqQiCHb+Q0jjIdwzg7oYu2uiltKmFcDxzSMqluqyCRQxGpTFUmSU4UuNTLZWII98I5Xe2CA43kzcIz/J8lLx21Ac6ZERLT2yc1ZY/dpE1rzGpIyQpZEEJg=}
